# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json, html ], fallback_format: json, prefer_extension: true }
            - { path: ^/, priorities: [ html ], fallback_format: html, prefer_extension: true }

    exception:
        enabled: true
#        codes:
#            Symfony\Component\HttpKernel\Exception\HttpException: 403
#        messages:
#            Symfony\Component\HttpKernel\Exception\HttpException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
