version: '2'

services:
  php-fpm:
    container_name: bindhq-php-fpm
    build:
      context: .
      dockerfile: docker/php8.2-fpm/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ${SYMFONY_APP_PATH}:/var/www/html
      - ./logs/symfony:/var/www/html/var/log
      - ./docker/php8.2-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php8.2-fpm/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - "9000"
    environment:
      - APP_ENV=${APP_ENV}
      - ENV_TYPE=symfony
      - ENABLE_XDEBUG=1
      - PHP_IDE_CONFIG=serverName=${SERVER_NAME}
  nginx:
    container_name: bindhq-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
        SERVER_NAME: ${SERVER_NAME}
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - .:/var/www/html
      - ./logs/nginx/:/var/log/nginx
  postgres:
    container_name: bindhq-postgres
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
